database:
    host: localhost
    port: 5432
    user: user
    password: password
    name: db

kafka:
    brokers:
        - "localhost:9091"
        - "localhost:9092"
        - "localhost:9093"
    topic: "orders"
    console-printing: true
