database:
    host: localhost
    port: 5432
    user: user
    password: password
    name: db

kafka:
    brokers:
        - "localhost:9091"
        - "localhost:9092"
        - "localhost:9093"
    topic: "orders"
    console-printing: true

redis:
    url: localhost:6379
    db: 0
    password: admin
    ttl-seconds: 60000000000

http:
    port: 8099