database:
    host: localhost
    port: 5432
    user: postgres
    password: admin
    name: ozon_hw3

kafka:
    brokers:
        - "localhost:9091"
        - "localhost:9092"
        - "localhost:9093"
    topic: "orders"
    console-printing: true
