global:
  scrape_interval: 15s

  external_labels:
    monitor: 'orders_service'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8099']